module.exports = {
  ci: {
    collect: {
      url: [
        'https://wellit.co.kr',
        'https://wellit.co.kr/product/detail.html?product_no=14',
        'https://wellit.co.kr/product/detail.html?product_no=202',
        'https://pronutrition.co.kr',
        'https://pronutrition.co.kr/product/detail.html?product_no=38',
        'https://pronutrition.co.kr/product/detail.html?product_no=86',
        'https://themedion.com',
        'https://themedion.com/product/detail.html?product_no=12',
        'https://themedion.com/product/detail.html?product_no=46',
	    'https://themedion.com/product/detail.html?product_no=99',
        'https://curicell.kr',
        'https://curicell.kr/product/detail.html?product_no=33',
	    'https://curicell.kr/product/detail.html?product_no=129',
        'https://celladix.co.kr',
        'https://celladix.co.kr/product/detail.html?product_no=10',
	    'https://celladix.co.kr/product/detail.html?product_no=169',
        'https://bifigen.com',
        'https://bifigen.com/product/detail.html?product_no=12',
	    'https://bifigen.com/product/detail.html?product_no=68',
        'https://housweet.co.kr',
	    'https://housweet.kr/product/detail.html?product_no=71',
        'https://housweet.co.kr/product/detail.html?product_no=74',
        'https://cleanery.co.kr',
        'https://cleanery.co.kr/product/detail.html?product_no=15',
        'https://hedn.kr',
        'https://hedn.kr/product/detail.html?product_no=64',
	    'https://lactomedi.com',
      	'https://lactomedi.com/collections/best-sellers',
      	'https://lactomedi.com/products/intimate-care-gel-for-women',
      	'https://celladix.us',
      	'https://celladix.us/collections/best-sellers',
      	'https://celladix.us/products/131-pore-clearing-serum',
      	'https://lactomedi.sg',
      	'https://lactomedi.sg/products/intimate-care-gel-for-women',
      	'https://celladix.sg',
      	'https://celladix.sg/products/https-celladix-sg-products-celladix-131-pore-clearing-serum',
      	'https://lactomedi.jp',
      	'https://lactomedi.jp/products/%E3%83%91%E3%83%92%E3%83%A5%E3%83%BC%E3%83%A0%E3%83%9F%E3%82%B9%E3%83%88',
      	'https://celladix.jp',
      	'https://celladix.jp/products/sebum-rebalancing-rx-131-ampoule',
       ],
      numberOfRuns: 5,
      output: ["html", "json"],
      settings: {
        formFactor: "desktop",
        screenEmulation: { disabled: true },
        throttlingMethod: "devtools",
        throttling: {
          rttMs: 40,
          throughputKbps: 10240,
          cpuSlowdownMultiplier: 1,
          requestLatencyMs: 0,
          downloadThroughputKbps: 0,
          uploadThroughputKbps: 0,
        },
		maxWaitForLoad: 90000,
      },
    },
    upload: {
      target: 'filesystem',
      outputDir: './results/desktop',
      reportFilenamePattern: 'report-pc-__url.host__-__index__'      
    }
  }
};
